name: floop
description: Dynamic values for widgets. Changes values from anywhere and affected widgets are updated automatically.
version: 0.4.0
author: Ignacio Catal√°n <icata2016@gmail.com>
homepage: https://github.com/icatalud/floop

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # meta: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  mockito: ^4.1.0
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
